# Generated by Django 4.2.16 on 2024-11-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_chatmessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='conversation_id',
            field=models.CharField(default='', editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
